# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './resource/login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QLineEdit

from gui.mainWinIns import main_window
from logic.user import User


class Ui_loginMain(object):
    def __init__(self):
        self.user_not_exist_msg = QMessageBox(QMessageBox.Critical, "错误", "用户不存在")
        self.msg_box = QMessageBox(QMessageBox.Critical, "错误", "密码错误")
        self.userHandle = User()

    def setupUi(self, loginMain):
        loginMain.setObjectName("loginMain")
        loginMain.resize(600, 318)
        loginMain.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(loginMain)
        self.centralwidget.setObjectName("centralwidget")
        self.input_user = QtWidgets.QLineEdit(self.centralwidget)
        self.input_user.setGeometry(QtCore.QRect(420, 90, 113, 22))
        self.input_user.setObjectName("input_user")
        self.user = QtWidgets.QLabel(self.centralwidget)
        self.user.setGeometry(QtCore.QRect(350, 90, 61, 21))
        self.user.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.user.setObjectName("user")
        self.input_pwd = QtWidgets.QLineEdit(self.centralwidget)
        self.input_pwd.setGeometry(QtCore.QRect(420, 120, 113, 22))
        self.input_pwd.setObjectName("input_pwd")
        self.input_pwd.setEchoMode(QLineEdit.Password)
        self.pwd = QtWidgets.QLabel(self.centralwidget)
        self.pwd.setGeometry(QtCore.QRect(350, 120, 61, 21))
        self.pwd.setTextFormat(QtCore.Qt.AutoText)
        self.pwd.setScaledContents(False)
        self.pwd.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.pwd.setWordWrap(False)
        self.pwd.setObjectName("pwd")
        self.type = QtWidgets.QLabel(self.centralwidget)
        self.type.setGeometry(QtCore.QRect(350, 150, 61, 21))
        self.type.setTextFormat(QtCore.Qt.AutoText)
        self.type.setScaledContents(False)
        self.type.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.type.setWordWrap(False)
        self.type.setObjectName("type")
        self.intput_type = QtWidgets.QComboBox(self.centralwidget)
        self.intput_type.setGeometry(QtCore.QRect(420, 150, 81, 22))
        self.intput_type.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.intput_type.setObjectName("intput_type")
        self.intput_type.addItems(['user', 'admin'])
        self.login = QtWidgets.QPushButton(self.centralwidget)
        self.login.setGeometry(QtCore.QRect(380, 200, 81, 26))
        self.login.setObjectName("login")
        self.login.clicked.connect(self.click_login)
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(480, 200, 81, 26))
        self.exit.setObjectName("exit")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(0, 20, 350, 250))
        self.logo.setStyleSheet("border-image: url(./resource/background/logo.png);width:300px;height:200px"
                                ";background-position: center;background-repeat: no-repeat;")
        self.logo.setText("")
        self.logo.setObjectName("logo")
        self.login_type = QtWidgets.QPushButton(self.centralwidget)
        self.login_type.setGeometry(QtCore.QRect(390, 30, 81, 26))
        self.login_type.setStyleSheet("#login_type{border:none;}\n"
                                      "#login_type:focus{color: rgb(255, 85, 255);}")
        self.login_type.setObjectName("login_type")
        self.register_type = QtWidgets.QPushButton(self.centralwidget)
        self.register_type.setGeometry(QtCore.QRect(470, 30, 81, 26))
        self.register_type.setStyleSheet("#register_type{border:none;}\n"
                                         "#register_type:focus{color: rgb(255, 85, 255);}")
        self.register_type.setObjectName("register_type")
        loginMain.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(loginMain)
        self.statusbar.setObjectName("statusbar")
        loginMain.setStatusBar(self.statusbar)

        self.retranslateUi(loginMain)
        QtCore.QMetaObject.connectSlotsByName(loginMain)

    def retranslateUi(self, loginMain):
        _translate = QtCore.QCoreApplication.translate
        loginMain.setWindowTitle(_translate("loginMain", "MainWindow"))
        self.user.setText(_translate("loginMain", "账号:"))
        self.pwd.setText(_translate("loginMain", "密码:"))
        self.type.setText(_translate("loginMain", "类型:"))
        self.login.setText(_translate("loginMain", "登陆"))
        self.exit.setText(_translate("loginMain", "退出"))
        self.login_type.setText(_translate("loginMain", "登陆"))
        self.register_type.setText(_translate("loginMain", "注册"))

    def click_login(self):
        # 获取用户名
        user_info = self.input_user.text()
        # 获取密码
        pwd_info = self.input_pwd.text()
        role_type = self.intput_type.currentText()
        res = self.userHandle.get_user(user_info, role_type)
        if res:
            if pwd_info == res[2]:
                self.main_win = main_window(user_info, role_type)
                self.main_win.show()
                self.close()
            else:
                self.msg_box.exec()
        else:
            self.user_not_exist_msg.exec()
