# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtWidgets

from gui.userIns import user_instance
from logic.HandTrackingModule import HandDetector
from logic.operation import Operation


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(431, 318)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(110, 20, 221, 261))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.user_info = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.user_info.setObjectName("user_info")
        self.verticalLayout.addWidget(self.user_info)
        self.user_info.clicked.connect(self.click_user_info)
        self.hand_control = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.hand_control.setObjectName("hand_control")
        self.verticalLayout.addWidget(self.hand_control)
        self.hand_control.clicked.connect(self.click_hand_control)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.user_info.setText(_translate("MainWindow", "用户配置"))
        self.hand_control.setText(_translate("MainWindow", "手势控制"))

    def init_default_config(self, user, role_type):
        self.user = user
        self.role_type = role_type

    def click_user_info(self):
        self.uIns = user_instance(self.user, self.role_type)
        self.uIns.show()

    def click_hand_control(self):
        detector = HandDetector(mode=False,  # 视频流图像
                                maxHands=1,  # 最多检测一只手
                                detectionCon=0.8,  # 最小检测置信度
                                minTrackCon=0.5)  # 最小跟踪置信度
        operation = Operation()
        operation.detect(detector)
